import { useMemo, useState } from 'react';
import { Brain, BookOpen, CalendarDays, CheckCircle2, ChevronRight, Clock3, Flame, Gauge, GraduationCap, Home, ListChecks, Menu, Moon, Plus, Search, Settings, Sparkles, Target, Trophy, X, Zap } from 'lucide-react';

type Subject = { name: string; code: string; mastery: number; topics: number; done: number; icon: string };
type Task = { subject: string; title: string; mins: number; why: string; type: string };
const subjects: Subject[] = [
  { name: 'Physics', code: '0625', mastery: 82, topics: 34, done: 28, icon: 'PHY' },
  { name: 'Chemistry', code: '0620', mastery: 58, topics: 36, done: 21, icon: 'CHEM' },
  { name: 'Mathematics', code: '', mastery: 88, topics: 42, done: 37, icon: 'MATH' },
  { name: 'English', code: '0500', mastery: 54, topics: 30, done: 16, icon: 'ENG' },
  { name: 'Computer Science', code: '0478', mastery: 71, topics: 31, done: 22, icon: 'CS' },
];
const tasks: Task[] = [
  { subject: 'Chemistry', title: 'Atomic structure — exam questions', mins: 35, why: 'Weak topic + repeated mistakes', type: 'Practice' },
  { subject: 'English', title: 'Directed writing: improve your structure', mins: 30, why: 'High-priority weakness', type: 'Learn' },
  { subject: 'Physics', title: 'Forces & motion — mini test', mins: 25, why: 'Revision due today', type: 'Test' },
];
const tone = (n: number) => n >= 85 ? 'strong' : n >= 50 ? 'mid' : 'weak';
const label = (n: number) => n >= 90 ? 'Mastered' : n >= 75 ? 'Strong' : n >= 60 ? 'Building' : 'Developing';

export default function App() {
  const [page, setPage] = useState('Home');
  const [dark, setDark] = useState(false);
  const [menu, setMenu] = useState(false);
  const [session, setSession] = useState(false);
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => subjects.filter(s => `${s.name}${s.code}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const nav = [['Home', Home], ['Study', BookOpen], ['My Subjects', GraduationCap], ['Planner', CalendarDays], ['Mistakes', ListChecks], ['Progress', Gauge], ['AI Coach', Brain], ['Settings', Settings]] as const;
  return <div className={dark ? 'app dark' : 'app'}>
    <aside className={menu ? 'sidebar open' : 'sidebar'}>
      <div className="brand"><div className="brandmark">M</div><div><b>MyStudies</b><span>Your study companion</span></div><button className="close" onClick={() => setMenu(false)}><X size={18}/></button></div>
      <nav>{nav.map(([name, Icon]) => <button key={name} className={page === name ? 'active' : ''} onClick={() => { setPage(name); setMenu(false); }}><Icon size={18}/><span>{name}</span>{name === 'Mistakes' && <em>7</em>}</button>)}</nav>
      <div className="sideBottom"><div className="streak"><Flame size={17}/><div><b>12 day streak</b><span>Keep it going</span></div></div><button className="profile"><div className="avatar">I</div><span>Ibrahim</span><ChevronRight size={16}/></button></div>
    </aside>
    <main><header><button className="hamb" onClick={() => setMenu(true)}><Menu/></button><div className="search"><Search size={17}/><input placeholder="Search subjects, topics, tasks…" value={query} onChange={e => setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><button className="iconbtn" onClick={() => setDark(v => !v)}><Moon size={18}/></button><button className="avatar top">I</button></header>
      {page === 'Home' ? <HomePage setSession={setSession}/> : page === 'Study' ? <Study setSession={setSession}/> : page === 'My Subjects' ? <SubjectsPage items={filtered} setSession={setSession}/> : page === 'Planner' ? <Planner/> : page === 'Mistakes' ? <Mistakes/> : page === 'Progress' ? <Progress/> : page === 'AI Coach' ? <Coach/> : <SettingsPage dark={dark} setDark={setDark}/>}</main>
    {session && <Session onClose={() => setSession(false)}/>}</div>;
}

function HomePage({setSession}:{setSession:(v:boolean)=>void}) { return <section className="page">
  <div className="welcome"><div><p className="eyebrow">SATURDAY · SEPTEMBER 12</p><h1>Good afternoon, Ibrahim.</h1><p className="muted">Your plan is ready. Let’s make today count.</p></div><div className="score"><div className="ring"><strong>74</strong><span>/100</span></div><div><b>Study health</b><span className="up">↑ 6% this week</span></div></div></div>
  <div className="hero"><div><div className="pill"><Sparkles size={15}/> AI recommendation</div><h2>What should I study?</h2><p>Start with Chemistry. Atomic structure is holding back your Chemistry mastery, and you have 35 minutes available.</p><button className="primary" onClick={() => setSession(true)}>Start recommended session <ChevronRight size={18}/></button></div><div className="heroOrb"><Brain size={48}/><span>Next best<br/>action</span></div></div>
  <div className="grid3"><Metric icon={<Target/>} label="Daily target" value="90 / 120 min" progress={75}/><Metric icon={<Flame/>} label="Streak" value="12 days" note="Best: 18 days"/><Metric icon={<Zap/>} label="Today’s XP" value="+240 XP" note="Level 8 · 2,140 XP"/></div>
  <div className="sectionHead"><div><h3>Needs attention</h3><p>Topics where focused practice will help most.</p></div></div>
  <div className="attention">{[['Chemistry','Atomic structure',58,'7 mistakes'],['English','Writing structure',54,'5 mistakes'],['Computer Science','Pseudocode',63,'3 mistakes']].map(x => <button className="attentionRow" key={String(x[1])} onClick={() => setSession(true)}><div className="subjectDot">{String(x[0]).slice(0,1)}</div><div className="grow"><b>{x[1]}</b><span>{x[0]} · {x[3]}</span></div><div className={`miniScore ${tone(Number(x[2]))}`}>{x[2]}%</div><ChevronRight size={17}/></button>)}</div>
  <div className="sectionHead"><div><h3>Today</h3><p>AI has arranged your highest-impact work first.</p></div></div>
  <div className="tasks">{tasks.map((t,i) => <button className="task" key={t.title} onClick={() => setSession(true)}><div className="taskTime"><Clock3 size={15}/>{t.mins}m</div><div className="grow"><span className="tag">{t.subject} · {t.type}</span><b>{t.title}</b><small>{t.why}</small></div><div className="taskNum">0{i+1}</div><ChevronRight size={18}/></button>)}</div>
</section>; }
function Metric({icon,label,value,progress,note}:{icon:React.ReactNode;label:string;value:string;progress?:number;note?:string}) { return <div className="metric"><div className="metricIcon">{icon}</div><span>{label}</span><strong>{value}</strong>{progress !== undefined ? <div className="bar"><i style={{width:`${progress}%`}}/></div> : <small>{note}</small>}</div>; }
function SubjectsPage({items,setSession}:{items:Subject[];setSession:(v:boolean)=>void}) { return <section className="page"><div className="pageTitle"><div><p className="eyebrow">YOUR SYLLABUS</p><h1>My Subjects</h1><p className="muted">Mastery is calculated from accuracy, difficulty, mistakes and recent performance.</p></div><button className="primary small"><Plus size={17}/> Add subject</button></div><div className="subjectGrid">{items.map(s => <div className="subjectCard" key={s.name}><div className="subjectTop"><div className="subjectIcon">{s.icon}</div><span className={`status ${tone(s.mastery)}`}>{label(s.mastery)}</span></div><h3>{s.name}</h3><p>{s.code || 'Core syllabus'} · {s.done}/{s.topics} topics covered</p><div className="mastery"><div><span>Mastery</span><b>{s.mastery}%</b></div><div className="bar"><i style={{width:`${s.mastery}%`}}/></div></div><button className="outline" onClick={() => setSession(true)}>Continue studying <ChevronRight size={16}/></button></div>)}</div></section>; }
function Planner() { return <section className="page"><div className="pageTitle"><div><p className="eyebrow">PLAN</p><h1>Planner</h1><p className="muted">Your work, arranged around deadlines and your available time.</p></div><button className="primary small"><Plus size={17}/> Add task</button></div><div className="tabs"><b>Today</b><span>This Week</span><span>Upcoming</span><span>Homework</span><span>Exams</span></div><div className="plannerDate"><h3>Saturday, Sep 12</h3><span>120 min target · 90 min planned</span></div>{tasks.map((t,i) => <div className="planRow" key={t.title}><div className="planCheck">{i === 0 ? <CheckCircle2 size={19}/> : <div/>}</div><div className="grow"><span>{t.subject} · {t.type}</span><b>{t.title}</b></div><strong>{t.mins} min</strong><button className="dots">•••</button></div>)}<div className="addLine"><Plus size={16}/> Add a task or study block</div><div className="exam"><div className="examIcon"><GraduationCap/></div><div className="grow"><span>UPCOMING EXAM · PHYSICS</span><b>Physics 0625</b><small>18 days left · 9/14 topics covered</small></div><div className="readiness"><b>78%</b><span>ready</span></div></div></section>; }
function Mistakes() { return <section className="page"><div className="pageTitle"><div><p className="eyebrow">LEARN FROM ERRORS</p><h1>Mistake Bank</h1><p className="muted">7 unresolved mistakes are influencing your next recommendations.</p></div></div><div className="filterbar"><button className="selected">All · 24</button><button>Unresolved · 7</button><button>Repeated · 5</button><button>Recent</button></div>{[['Chemistry','Atomic structure — electron arrangement','forgot the rule','3× · Sep 10'],['English','Formal letter — paragraph structure','misunderstood the question','2× · Sep 9']].map(x => <div className="mistake" key={x[1]}><span className={`tag ${x[0] === 'Chemistry' ? 'chem' : 'eng'}`}>{x[0]}</span><h3>{x[1]}</h3><p>Why it went wrong: <b>{x[2]}</b></p><div className="mistakeBottom"><span>Repeated {x[3]}</span><button className="outline">Review <ChevronRight size={15}/></button></div></div>)}</section>; }
function Progress() { return <section className="page"><div className="pageTitle"><div><p className="eyebrow">YOUR PERFORMANCE</p><h1>Progress</h1><p className="muted">A clearer picture of how your study is translating into mastery.</p></div></div><div className="progressHero"><div><span>Overall mastery</span><strong>73%</strong><p className="up">↑ 8% over the last 30 days</p></div><div className="bars">{subjects.map(s => <div key={s.name}><span>{s.name}</span><div className="bar"><i style={{width:`${s.mastery}%`}}/></div><b>{s.mastery}%</b></div>)}</div></div><div className="insights"><div><Sparkles/><b>AI insight</b><p>Chemistry and English are your biggest opportunities. Fixing repeated Chemistry errors could raise overall mastery fastest.</p></div><div><Trophy/><b>Level 8</b><p>2,140 XP earned. 360 XP to Level 9.</p></div></div></section>; }
function Coach() { const [msg,setMsg]=useState(''); const [reply,setReply]=useState(''); const send=()=>{if(!msg.trim())return;setReply('Based on your current mastery and mistakes, I would start with Chemistry → Atomic structure.');setMsg('');}; return <section className="page coach"><div className="coachHead"><div className="coachLogo"><Brain/></div><p className="eyebrow">YOUR AI STUDY COACH</p><h1>Let’s figure it out.</h1><p className="muted">I know your subjects, mastery, mistakes, exams and study history. Ask me anything.</p></div><div className="suggestions">{['What should I study now?','Why am I struggling with Chemistry?','I only have 30 minutes.','Make this topic easier.'].map(q => <button key={q} onClick={() => setMsg(q)}>{q}</button>)}</div><div className="chat"><div className="bubble ai"><Sparkles size={15}/><span>{reply || <>Based on your current mastery and recent mistakes, I’d start with <b>Chemistry → Atomic structure</b>. You have 35 minutes, so I can run a focused learn → practice → mini-test session.</>}</span></div><div className="chatInput"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask your coach…"/><button className="primary" onClick={send}>Send</button></div></div></section>; }
function Study({setSession}:{setSession:(v:boolean)=>void}) { return <section className="page"><div className="pageTitle"><div><p className="eyebrow">STUDY</p><h1>Choose your next session</h1><p className="muted">Every session is designed to improve mastery, not just tick a box.</p></div></div><div className="studyOptions"><div className="bigStudy"><Sparkles/><h2>Recommended for you</h2><h3>Chemistry · Atomic structure</h3><p>35 min · 3 weak concepts · 7 mistakes to fix</p><button className="primary" onClick={()=>setSession(true)}>Start session <ChevronRight/></button></div><div className="studyList"><button onClick={()=>setSession(true)}><Target/><span><b>Practice weak topics</b><small>Best for improving mastery quickly</small></span><ChevronRight/></button><button><ListChecks/><span><b>Review mistake bank</b><small>7 unresolved mistakes</small></span><ChevronRight/></button><button><GraduationCap/><span><b>Exam prep</b><small>Physics exam in 18 days</small></span><ChevronRight/></button></div></div></section>; }
function SettingsPage({dark,setDark}:{dark:boolean;setDark:(v:boolean)=>void}) { return <section className="page"><div className="pageTitle"><div><p className="eyebrow">PREFERENCES</p><h1>Settings</h1></div></div><div className="settings"><div><b>Appearance</b><span>Choose your preferred interface theme.</span><button className="toggle" onClick={()=>setDark(!dark)}><i className={dark?'on':''}/>{dark?'Dark mode':'Light mode'}</button></div><div><b>Daily study target</b><span>Your current target is 120 minutes.</span><button className="outline">Edit target</button></div><div><b>Subjects & syllabus</b><span>Manage subjects and import your syllabus.</span><button className="outline">Manage syllabus</button></div></div></section>; }
function Session({onClose}:{onClose:()=>void}) { const [step,setStep]=useState(1); const [answer,setAnswer]=useState(''); return <div className="modal"><div className="session"><header><div><span className="tag">CHEMISTRY · 0620</span><h2>Atomic structure</h2></div><button className="iconbtn" onClick={onClose}><X/></button></header><div className="sessionProgress"><i style={{width:`${step/3*100}%`}}/></div>{step===1?<div className="sessionBody"><p className="eyebrow">STEP 1 · LEARN</p><h1>Atoms are built from three main particles.</h1><p className="explain">Protons and neutrons sit in the nucleus. Electrons move around the nucleus in shells. The number of protons tells you which element it is.</p><div className="particleGrid"><div><b>Proton</b><span>+1 charge · nucleus</span></div><div><b>Neutron</b><span>0 charge · nucleus</span></div><div><b>Electron</b><span>−1 charge · shells</span></div></div><button className="primary wide" onClick={()=>setStep(2)}>I understand · Active recall <ChevronRight/></button></div>:step===2?<div className="sessionBody"><p className="eyebrow">STEP 2 · ACTIVE RECALL</p><h1>How many electrons are in a neutral atom with 6 protons?</h1><p className="explain">A neutral atom has equal numbers of protons and electrons.</p><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer"/><button className="primary wide" onClick={()=>setStep(3)}>Check answer · Mini-test <ChevronRight/></button></div>:<div className="sessionBody"><p className="eyebrow">STEP 3 · MINI-TEST</p><h1>Session complete.</h1><p className="explain">You finished this focused session. In the full version, your answers, mistakes, XP and mastery will update automatically.</p><div className="particleGrid"><div><b>+35 min</b><span>Study time</span></div><div><b>+120 XP</b><span>Earned</span></div><div><b>Next</b><span>Review mistakes</span></div></div><button className="primary wide" onClick={onClose}>Finish session <CheckCircle2/></button></div>}</div></div>; }
