import {useEffect,useMemo,useState} from 'react';
import type {FormEvent} from 'react';
import {ArrowUpRight,Brain,BookOpen,CalendarDays,CheckCircle2,ChevronRight,Clock3,Flame,Gauge,GraduationCap,Home,ListChecks,Menu,Moon,Plus,Search,Settings,Sparkles,Target,Trophy,X,Zap,Trash2,RotateCcw} from 'lucide-react';

type Subject={name:string;code:string;mastery:number;topics:number;done:number;accent:string};
type Task={id:number;subject:string;title:string;mins:number;why:string;type:string;done:boolean};
type Mistake={id:number;subject:string;topic:string;why:string;repeats:number;resolved:boolean};
type Exam={id:number;subject:string;name:string;date:string;topics:string};
type Stage='learn'|'recall'|'practice'|'done';
const content:Record<string,{topic:string;learn:string;recall:string;question:string;answer:string;tip:string}>={
 Physics:{topic:'Forces & motion',learn:'A resultant force changes an object’s motion. For the same mass, a larger resultant force produces a larger acceleration.',recall:'State Newton’s second law and say what happens to acceleration when force increases.',question:'A 4 kg object has a resultant force of 12 N. Calculate its acceleration.',answer:'3 m/s²',tip:'Use F = ma, so a = F ÷ m.'},
 Chemistry:{topic:'Atomic structure',learn:'Atoms contain protons and neutrons in the nucleus, with electrons around the nucleus. Proton number identifies the element.',recall:'What are the charges of a proton, neutron and electron?',question:'A neutral atom has 11 protons. How many electrons does it have?',answer:'11 electrons',tip:'Neutral atoms have equal numbers of protons and electrons.'},
 Mathematics:{topic:'Algebra & equations',learn:'An equation is balanced. Whatever you do to one side, do to the other side.',recall:'What should you do to both sides when you subtract a term?',question:'Solve 3x + 5 = 20.',answer:'x = 5',tip:'Subtract 5, then divide by 3.'},
 English:{topic:'Directed writing',learn:'Good directed writing answers the task, uses the right tone and organizes ideas clearly for the intended reader.',recall:'Give two checks you should make before writing a directed-writing response.',question:'Write a formal opening sentence to a school principal requesting a change.',answer:'Example: I am writing to request that the school consider...',tip:'Make the purpose clear and keep the tone formal.'},
 'Computer Science':{topic:'Pseudocode — selection',learn:'Selection lets a program choose between paths. IF checks a condition; ELSE handles the alternative.',recall:'What is the difference between IF and ELSE?',question:'Write pseudocode that outputs PASS when mark is 50 or higher, otherwise FAIL.',answer:'IF mark >= 50 THEN OUTPUT "PASS" ELSE OUTPUT "FAIL"',tip:'Start with the condition, then handle the alternative with ELSE.'}
};
const initialSubjects:Subject[]=[
 {name:'Physics',code:'0625',mastery:82,topics:34,done:28,accent:'sage'},
 {name:'Chemistry',code:'0620',mastery:58,topics:36,done:21,accent:'gold'},
 {name:'Mathematics',code:'',mastery:88,topics:42,done:37,accent:'blue'},
 {name:'English',code:'0500',mastery:54,topics:30,done:16,accent:'violet'},
 {name:'Computer Science',code:'0478',mastery:71,topics:31,done:22,accent:'green'}
];
const initialTasks:Task[]=[
 {id:1,subject:'Chemistry',title:'Atomic structure — exam questions',mins:35,why:'Weak topic + repeated mistakes',type:'Practice',done:false},
 {id:2,subject:'English',title:'Directed writing — improve structure',mins:30,why:'High-priority weakness',type:'Learn',done:false},
 {id:3,subject:'Physics',title:'Forces & motion — mini test',mins:25,why:'Revision due today',type:'Test',done:false}
];
const initialMistakes:Mistake[]=[
 {id:1,subject:'Chemistry',topic:'Atomic structure — electron arrangement',why:'Forgot the rule',repeats:3,resolved:false},
 {id:2,subject:'English',topic:'Formal letter — paragraph structure',why:'Misunderstood the question',repeats:2,resolved:false},
 {id:3,subject:'Computer Science',topic:'Pseudocode — selection',why:'Logic error',repeats:1,resolved:true}
];
const initialExams:Exam[]=[{id:1,subject:'Physics',name:'Physics 0625',date:'2026-09-30',topics:'Forces & motion, energy, waves'}];
const tone=(n:number)=>n>=85?'strong':n>=50?'mid':'weak';
const label=(n:number)=>n>=90?'Mastered':n>=75?'Strong':n>=60?'Building':'Developing';
const key='mystudies-v7';
function load<T>(k:string,f:T):T{try{const x=localStorage.getItem(`${key}-${k}`);return x?JSON.parse(x):f}catch{return f}}
function save<T>(k:string,v:T){try{localStorage.setItem(`${key}-${k}`,JSON.stringify(v))}catch{}}

export default function App(){
 const [page,setPage]=useState('Home'),[dark,setDark]=useState(()=>load('dark',false)),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[target,setTarget]=useState(()=>load('target',120)),[xp,setXp]=useState(()=>load('xp',2140));
 const [subjects,setSubjects]=useState<Subject[]>(()=>load('subjects',initialSubjects)); const [tasks,setTasks]=useState<Task[]>(()=>load('tasks',initialTasks)); const [mistakes,setMistakes]=useState<Mistake[]>(()=>load('mistakes',initialMistakes)); const [exams,setExams]=useState<Exam[]>(()=>load('exams',initialExams));
 const [session,setSession]=useState<{task:Task;stage:Stage}|null>(null);
 useEffect(()=>save('dark',dark),[dark]);useEffect(()=>save('target',target),[target]);useEffect(()=>save('xp',xp),[xp]);useEffect(()=>save('subjects',subjects),[subjects]);useEffect(()=>save('tasks',tasks),[tasks]);useEffect(()=>save('mistakes',mistakes),[mistakes]);useEffect(()=>save('exams',exams),[exams]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?subjects.filter(s=>`${s.name} ${s.code}`.toLowerCase().includes(q)):subjects},[subjects,query]);
 const overall=Math.round(subjects.reduce((a,s)=>a+s.mastery,0)/subjects.length),doneMins=tasks.filter(t=>t.done).reduce((a,t)=>a+t.mins,0),unresolved=mistakes.filter(m=>!m.resolved).length;
 const start=(subject:string,title?:string)=>{const c=content[subject]||content.Physics;setSession({task:{id:Date.now(),subject,title:title||c.topic,mins:25,why:'Recommended from your progress',type:'Study',done:false},stage:'learn'})};
 const finish=()=>{if(!session)return;setTasks(p=>p.map(t=>t.subject===session.task.subject&&t.title===session.task.title?{...t,done:true}:t));setSubjects(p=>p.map(s=>s.name===session.task.subject?{...s,mastery:Math.min(100,s.mastery+2),done:Math.min(s.topics,s.done+1)}:s));setXp(x=>x+40);setSession(null)};
 const nav=[['Home',Home],['Study',BookOpen],['My Subjects',GraduationCap],['Planner',CalendarDays],['Mistakes',ListChecks],['Progress',Gauge],['AI Coach',Brain],['Settings',Settings]] as const;
 return <div className={dark?'app dark':'app'}><aside className={menu?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark">M</div><div><b>MyStudies</b><span>Your study companion</span></div><button className="close" onClick={()=>setMenu(false)}><X size={18}/></button></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);setMenu(false)}}><I size={18}/><span>{n}</span>{n==='Mistakes'&&unresolved>0&&<em>{unresolved}</em>}</button>)}</nav><div className="sideBottom"><div className="streak"><Flame size={17}/><div><b>12 day streak</b><span>{doneMins}/{target} min today</span></div></div><button className="profile" onClick={()=>setPage('Settings')}><div className="avatar">I</div><span>Ibrahim</span></button></div></aside><main><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&query.trim())setPage('My Subjects')}} placeholder="Search…"/><kbd>Ctrl K</kbd></div><button className="iconbtn" onClick={()=>setDark(v=>!v)}><Moon size={18}/></button><button className="avatar top" onClick={()=>setPage('Settings')}>I</button></header>
 {page==='Home'&&<Home subjects={subjects} tasks={tasks} overall={overall} doneMins={doneMins} target={target} xp={xp} start={start} setPage={setPage}/>} 
 {page==='Study'&&<Study subjects={subjects} tasks={tasks} start={start}/>} 
 {page==='My Subjects'&&<Subjects items={filtered} start={start} onAdd={()=>setSubjects(p=>[...p,{name:`Subject ${p.length+1}`,code:'',mastery:0,topics:0,done:0,accent:'green'}])}/>} 
 {page==='Planner'&&<Planner tasks={tasks} exams={exams} setTasks={setTasks} setExams={setExams}/>} 
 {page==='Mistakes'&&<Mistakes mistakes={mistakes} setMistakes={setMistakes} start={start}/>} 
 {page==='Progress'&&<Progress subjects={subjects} overall={overall} xp={xp} doneMins={doneMins} target={target}/>} 
 {page==='AI Coach'&&<Coach subjects={subjects} mistakes={mistakes} tasks={tasks} start={start}/>} 
 {page==='Settings'&&<SettingsPage dark={dark} setDark={setDark} target={target} setTarget={setTarget} reset={()=>{setSubjects(initialSubjects);setTasks(initialTasks);setMistakes(initialMistakes);setExams(initialExams);setXp(2140);setTarget(120)}}/>}
 </main>{session&&<Session task={session.task} stage={session.stage} setStage={stage=>setSession({task:session.task,stage})} close={()=>setSession(null)} finish={finish}/>}</div>
}

function Home({subjects,tasks,overall,doneMins,target,xp,start,setPage}:{subjects:Subject[];tasks:Task[];overall:number;doneMins:number;target:number;xp:number;start:(s:string,t?:string)=>void;setPage:(p:string)=>void}){const next=tasks.find(t=>!t.done)||tasks[0];return <section className="page"><div className="welcome reveal"><div><p className="eyebrow">SATURDAY · SEPTEMBER 12</p><h1>Good afternoon, Ibrahim.</h1><p className="muted">MyStudies already knows what needs work.</p></div><div className="score"><div className="ring"><strong>{overall}</strong><span>/100</span></div><div><b>Study health</b><span className="up">↑ 6% this week</span></div></div></div><div className="hero reveal delay1"><div><div className="pill"><Sparkles size={15}/> AI recommendation</div><h2>What should I study?</h2><p>{next?`${next.subject} → ${next.title} is your highest-impact next step.`:'Choose any subject to begin.'}</p><button className="primary heroButton" onClick={()=>next?start(next.subject,next.title):start('Chemistry')}>Start session <ArrowUpRight size={18}/></button></div><div className="heroOrb float"><div className="orbCore"><Brain size={34}/></div><span>Next best<br/>action</span></div></div><div className="grid3 reveal delay2"><Metric icon={<Target/>} label="Daily target" value={`${doneMins}/${target} min`} progress={Math.min(100,Math.round(doneMins/Math.max(target,1)*100))}/><Metric icon={<Flame/>} label="Streak" value="12 days" note="Keep it going"/><Metric icon={<Zap/>} label="XP" value={`+${Math.max(0,xp-2140)}`} note={`${xp} total`}/></div><div className="sectionHead"><div><h3>Needs attention</h3><p>Weak areas get priority.</p></div><button className="ghost" onClick={()=>setPage('My Subjects')}>Subjects <ChevronRight size={14}/></button></div><div className="attention">{subjects.filter(s=>s.mastery<75).map(s=><button key={s.name} className="attentionRow interactive" onClick={()=>start(s.name)}><div className={`subjectDot ${s.accent}`}>{s.name[0]}</div><div className="grow"><b>{s.name}</b><span>{label(s.mastery)} · {s.done}/{s.topics} topics</span></div><strong className={`miniScore ${tone(s.mastery)}`}>{s.mastery}%</strong><ChevronRight size={17}/></button>)}</div><div className="sectionHead"><div><h3>Today</h3><p>Real progress, not fake checkboxes.</p></div><button className="ghost" onClick={()=>setPage('Planner')}>Planner <ChevronRight size={14}/></button></div><div className="tasks">{tasks.map((t,i)=><button key={t.id} className={`task interactive ${t.done?'done':''}`} onClick={()=>start(t.subject,t.title)}><div className="taskTime">{t.done?<CheckCircle2 size={15}/>:<Clock3 size={15}/>} {t.mins}m</div><div className="grow"><span className="tag">{t.subject} · {t.type}</span><b>{t.title}</b><small>{t.done?'Completed':t.why}</small></div><div className="taskNum">0{i+1}</div><ChevronRight size={18}/></button>)}</div></section>}
function Metric({icon,label,value,progress,note}:{icon:React.ReactNode;label:string;value:string;progress?:number;note?:string}){return <div className="metric lift"><div className="metricIcon">{icon}</div><span>{label}</span><strong>{value}</strong>{progress!==undefined?<div className="bar"><i style={{width:`${progress}%`}}/></div>:<small>{note}</small>}</div>}

function Study({subjects,tasks,start}:{subjects:Subject[];tasks:Task[];start:(s:string,t?:string)=>void}){const weak=[...subjects].sort((a,b)=>a.mastery-b.mastery)[0];return <section className="page"><div className="pageTitle"><div><p className="eyebrow">STUDY</p><h1>Choose what to work on</h1><p className="muted">Every subject launches subject-correct content.</p></div></div><div className="studyOptions"><div className="bigStudy lift"><div className="bigStudyIcon"><Sparkles/></div><span className="tag light">RECOMMENDED</span><h2>{weak.name} · {content[weak.name].topic}</h2><p>25 min · Learn → Active recall → Exam practice</p><button className="primary" onClick={()=>start(weak.name)}>Start {weak.name} <ChevronRight/></button></div><div className="studyList">{subjects.slice(0,3).map(s=><button key={s.name} className="studyAction lift" onClick={()=>start(s.name)}><div className={`subjectDot ${s.accent}`}>{s.name[0]}</div><span><b>{s.name}</b><small>{content[s.name].topic} · {s.mastery}% mastery</small></span><ChevronRight/></button>)}<button className="studyAction lift" onClick={()=>{const t=tasks.find(x=>!x.done);if(t)start(t.subject,t.title)}}><Clock3/><span><b>Continue today’s plan</b><small>Pick up your next scheduled task</small></span><ChevronRight/></button></div></div></section>}
function Subjects({items,start,onAdd}:{items:Subject[];start:(s:string,t?:string)=>void;onAdd:()=>void}){return <section className="page"><div className="pageTitle"><div><p className="eyebrow">YOUR SYLLABUS</p><h1>My Subjects</h1><p className="muted">English opens English. Physics opens Physics. No mixed content.</p></div><button className="primary small" onClick={onAdd}><Plus size={17}/> Add subject</button></div><div className="subjectGrid">{items.map(s=><div className={`subjectCard lift ${s.accent}`} key={s.name}><div className="subjectTop"><div className="subjectIcon">{s.name.slice(0,4).toUpperCase()}</div><span className={`status ${tone(s.mastery)}`}>{label(s.mastery)}</span></div><h3>{s.name}</h3><p>{s.code||'Core syllabus'} · {s.done}/{s.topics} topics</p><div className="mastery"><div><span>Mastery</span><b>{s.mastery}%</b></div><div className="bar"><i style={{width:`${s.mastery}%`}}/></div></div><div className="subjectActions"><button className="outline" onClick={()=>start(s.name)}>Study {s.name} <ChevronRight size={15}/></button><button className="miniButton" onClick={()=>start(s.name,`${content[s.name].topic} mini test`)}>Test</button></div></div>)}</div></section>}

function Planner({tasks,exams,setTasks,setExams}:{tasks:Task[];exams:Exam[];setTasks:React.Dispatch<React.SetStateAction<Task[]>>;setExams:React.Dispatch<React.SetStateAction<Exam[]>>}){const[tab,setTab]=useState('Today'),[newTask,setNewTask]=useState(''),[show,setShow]=useState(false),[exam,setExam]=useState(''),[showExam,setShowExam]=useState(false);const add=(e:FormEvent)=>{e.preventDefault();if(!newTask.trim())return;setTasks(p=>[...p,{id:Date.now(),subject:'Chemistry',title:newTask.trim(),mins:30,why:'Added by you',type:'Study',done:false}]);setNewTask('');setShow(false)};const addExam=(e:FormEvent)=>{e.preventDefault();if(!exam.trim())return;setExams(p=>[...p,{id:Date.now(),subject:'Physics',name:exam,date:'2026-10-10',topics:'Add topics later'}]);setExam('');setShowExam(false)};return <section className="page"><div className="pageTitle"><div><p className="eyebrow">PLAN</p><h1>Planner</h1><p className="muted">Tasks, homework and exams in one place.</p></div><div className="actionRow"><button className="outline" onClick={()=>setShowExam(v=>!v)}><GraduationCap size={15}/> Add exam</button><button className="primary small" onClick={()=>setShow(v=>!v)}><Plus size={17}/> Add task</button></div></div><div className="tabs">{['Today','This Week','Upcoming','Homework','Exams'].map(t=><button key={t} className={tab===t?'tabActive':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Exams'?<div className="examList">{exams.map(e=><div className="examCard lift" key={e.id}><div className="examIcon"><GraduationCap/></div><div className="grow"><span>EXAM · {e.subject}</span><b>{e.name}</b><small>{e.date} · {e.topics}</small></div><button className="iconOnly" onClick={()=>setExams(p=>p.filter(x=>x.id!==e.id))}><Trash2 size={16}/></button></div>)}</div>:<><div className="plannerDate"><h3>Saturday, Sep 12</h3><span>{tasks.filter(t=>t.done).reduce((a,t)=>a+t.mins,0)} min done</span></div><div className="planList">{tasks.map(t=><div className={`planRow ${t.done?'done':''}`} key={t.id}><button className="planCheck" onClick={()=>setTasks(p=>p.map(x=>x.id===t.id?{...x,done:!x.done}:x))}>{t.done?<CheckCircle2 size={19}/>:<CircleIcon/>}</button><div className="grow"><span>{t.subject} · {t.type}</span><b>{t.title}</b><small>{t.why}</small></div><strong>{t.mins}m</strong><button className="iconOnly" onClick={()=>setTasks(p=>p.filter(x=>x.id!==t.id))}><Trash2 size={15}/></button></div>)}</div></>}{show&&<div className="inlineForm"><form onSubmit={add}><input autoFocus value={newTask} onChange={e=>setNewTask(e.target.value)} placeholder="Task title"/><button className="primary small">Save</button></form></div>}{showExam&&<div className="inlineForm"><form onSubmit={addExam}><input autoFocus value={exam} onChange={e=>setExam(e.target.value)} placeholder="Exam name"/><button className="primary small">Save exam</button></form></div>}</section>}
function CircleIcon(){return <span className="circleIcon"/>}

function Mistakes({mistakes,setMistakes,start}:{mistakes:Mistake[];setMistakes:React.Dispatch<React.SetStateAction<Mistake[]>>;start:(s:string,t?:string)=>void}){const[filter,setFilter]=useState('All');const list=mistakes.filter(m=>filter==='All'||filter==='Unresolved'&&!m.resolved||filter==='Repeated'&&m.repeats>1);return <section className="page"><div className="pageTitle"><div><p className="eyebrow">LEARN FROM ERRORS</p><h1>Mistake Bank</h1><p className="muted">Mistakes shape future recommendations.</p></div></div><div className="filterbar">{['All','Unresolved','Repeated'].map(f=><button className={filter===f?'selected':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div>{list.map(m=><div className={`mistake lift ${m.resolved?'resolved':''}`} key={m.id}><span className="tag">{m.subject}</span><h3>{m.topic}</h3><p>Why it went wrong: <b>{m.why}</b></p><div className="mistakeBottom"><span>{m.repeats}× repeated</span><div className="actionRow"><button className="outline" onClick={()=>start(m.subject,m.topic)}>Review</button><button className="miniButton" onClick={()=>setMistakes(p=>p.map(x=>x.id===m.id?{...x,resolved:!x.resolved}:x))}>{m.resolved?'Reopen':'Resolve'}</button></div></div></div>)}</section>}
function Progress({subjects,overall,xp,doneMins,target}:{subjects:Subject[];overall:number;xp:number;doneMins:number;target:number}){return <section className="page"><div className="pageTitle"><div><p className="eyebrow">YOUR PERFORMANCE</p><h1>Progress</h1></div></div><div className="progressHero lift"><div><span>Overall mastery</span><strong>{overall}%</strong><p className="up">↑ 8% over 30 days</p></div><div className="bars">{subjects.map(s=><div key={s.name}><span>{s.name}</span><div className="bar"><i style={{width:`${s.mastery}%`}}/></div><b>{s.mastery}%</b></div>)}<div><span>Daily target</span><div className="bar"><i style={{width:`${Math.min(100,Math.round(doneMins/Math.max(target,1)*100))}%`}}/></div><b>{doneMins}/{target}</b></div></div></div><div className="insights"><div className="insightCard lift"><Sparkles/><b>AI insight</b><p>Focus first on {[...subjects].sort((a,b)=>a.mastery-b.mastery)[0].name}. It currently has the lowest mastery.</p></div><div className="insightCard lift"><Trophy/><b>{Math.floor(xp/500)} XP level</b><p>{xp} total XP earned.</p></div></div></section>}
function Coach({subjects,mistakes,tasks,start}:{subjects:Subject[];mistakes:Mistake[];tasks:Task[];start:(s:string,t?:string)=>void}){const[msg,setMsg]=useState(''),[reply,setReply]=useState('');const send=(text=msg)=>{if(!text.trim())return;const weak=[...subjects].sort((a,b)=>a.mastery-b.mastery)[0],rep=mistakes.find(m=>!m.resolved&&m.repeats>1);setReply(rep?`Start with ${rep.subject} → ${rep.topic}. You have ${rep.repeats} repeated mistakes there.`:`Start with ${weak.name}. It is currently ${weak.mastery}% mastery.`);setMsg('')};return <section className="page coach"><div className="coachHead"><div className="coachLogo"><Brain/></div><p className="eyebrow">YOUR AI STUDY COACH</p><h1>Let’s figure it out.</h1><p className="muted">Ask what to study, why you are struggling, or what to do with limited time.</p></div><div className="suggestions">{['What should I study now?','Why am I struggling?','I only have 30 minutes.'].map(q=><button key={q} onClick={()=>send(q)}>{q}</button>)}</div><div className="chat"><div className="bubble ai"><Sparkles size={15}/><span>{reply||`I would start with ${[...subjects].sort((a,b)=>a.mastery-b.mastery)[0].name}.`}</span></div><div className="chatInput"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask your coach…"/><button className="primary" onClick={()=>send()}>Send</button></div></div><div className="coachActions"><button className="primary" onClick={()=>start([...subjects].sort((a,b)=>a.mastery-b.mastery)[0].name)}>Start recommended session <ChevronRight/></button><span>{tasks.filter(t=>!t.done).length} tasks left · {mistakes.filter(m=>!m.resolved).length} unresolved mistakes</span></div></section>}
function SettingsPage({dark,setDark,target,setTarget,reset}:{dark:boolean;setDark:(v:boolean)=>void;target:number;setTarget:(v:number)=>void;reset:()=>void}){const[t,setT]=useState(String(target));return <section className="page"><div className="pageTitle"><div><p className="eyebrow">PREFERENCES</p><h1>Settings</h1></div></div><div className="settings"><div className="settingsRow"><div><b>Appearance</b><span>Light or dark mode.</span></div><button className="toggle" onClick={()=>setDark(!dark)}><i className={dark?'on':''}/>{dark?'Dark':'Light'}</button></div><div className="settingsRow"><div><b>Daily study target</b><span>Used by the dashboard.</span></div><div className="inlineSetting"><input type="number" min="15" max="480" value={t} onChange={e=>setT(e.target.value)}/><span>min</span><button className="outline" onClick={()=>setTarget(Math.max(15,Math.min(480,Number(t)||120)))}>Save</button></div></div><div className="settingsRow danger"><div><b>Reset demo data</b><span>Restore sample data.</span></div><button className="outline" onClick={reset}><RotateCcw size={15}/> Reset</button></div></div></section>}

function Session({task,stage,setStage,close,finish}:{task:Task;stage:Stage;setStage:(s:Stage)=>void;close:()=>void;finish:()=>void}){const c=content[task.subject]||content.Physics;const[a,setA]=useState(''),[show,setShow]=useState(false);return <div className="modal"><div className="sessionCard"><header className="sessionHead"><div><span className="tag">{task.subject}</span><h2>{c.topic}</h2></div><button className="iconOnly" onClick={close}><X/></button></header><div className="sessionProgress"><i className={stage==='learn'?'active':''}/><i className={stage==='recall'?'active':''}/><i className={stage==='practice'?'active':''}/><i className={stage==='done'?'active':''}/></div>{stage==='learn'&&<div className="sessionBody stepIn"><div className="sessionBadge"><Brain/></div><p className="eyebrow">LEARN</p><h3>{c.topic}</h3><p className="sessionIntro">{c.learn}</p><div className="keyTip"><Sparkles size={16}/><span><b>Coach tip</b>{c.tip}</span></div><button className="primary sessionNext" onClick={()=>setStage('recall')}>Active recall <ChevronRight/></button></div>}{stage==='recall'&&<div className="sessionBody stepIn"><p className="eyebrow">ACTIVE RECALL</p><h3>{c.recall}</h3><textarea value={a} onChange={e=>setA(e.target.value)} placeholder="Type what you remember…"/><button className="primary sessionNext" onClick={()=>setStage('practice')}>Continue <ChevronRight/></button></div>}{stage==='practice'&&<div className="sessionBody stepIn"><p className="eyebrow">EXAM PRACTICE</p><h3>{c.question}</h3><textarea value={a} onChange={e=>setA(e.target.value)} placeholder="Your answer…"/><button className="outline" onClick={()=>setShow(v=>!v)}>{show?'Hide answer':'Show answer'}</button>{show&&<div className="answerBox"><b>Correct answer</b><p>{c.answer}</p><span>{c.tip}</span></div>}<button className="primary sessionNext" onClick={()=>setStage('done')}>Finish session <CheckCircle2/></button></div>}{stage==='done'&&<div className="sessionBody completeState stepIn"><div className="successOrb"><CheckCircle2 size={38}/></div><p className="eyebrow">COMPLETE</p><h3>{c.topic} finished.</h3><p className="sessionIntro">+40 XP · {task.subject} mastery updated.</p><button className="primary sessionNext" onClick={finish}>Back to MyStudies <ArrowUpRight/></button></div>}</div></div>}
